#include "nightwalker/core/Runtime.h"
#include <Windows.h>
#include <array>
#include <filesystem>
#include <string>
#include <utility>
#include "nightwalker/Version.h"
#include "nightwalker/narrative/NarrativeSettingsLoader.h"
#include "nightwalker/systems/SaintDenisSettingsLoader.h"
namespace nightwalker::core{
namespace{bool ModulePath(HMODULE m,std::filesystem::path&o){if(!m)return false;std::array<wchar_t,32768>b{};DWORD n=::GetModuleFileNameW(m,b.data(),(DWORD)b.size());if(!n||n>=b.size())return false;o=std::filesystem::path(std::wstring_view(b.data(),n));return true;}}
Runtime::Runtime():bossHudController_(gameApi_,gameCombatApi_,gameFeedingApi_,gamePhysicalApi_,gameBossBarApi_,logger_,config_),narrativeController_(gameBossBarApi_,gameNarrativeAudioApi_,logger_,config_),debugVampireSpawner_(gameApi_,bossRegistry_,logger_,config_),shadowstepController_(gameApi_,gameCombatApi_,logger_,config_),feedingController_(gameApi_,gameCombatApi_,gameFeedingApi_,logger_,config_),vampireCombatController_(gameApi_,gameCombatApi_,gameFeedingApi_,gameMovementApi_,gamePhysicalApi_,debugVampireSpawner_,feedingController_,logger_,config_),saintDenisDirector_(gameApi_,gameCombatApi_,gameEncounterApi_,gamePresentationApi_,bossRegistry_,narrativeController_,bossHudController_,logger_,config_),vampireAiController_(gameApi_,gameCombatApi_,gamePresentationApi_,debugVampireSpawner_,vampireCombatController_,logger_,config_),movementController_(gameApi_,gameCombatApi_,gameMovementApi_,gamePresentationApi_,debugVampireSpawner_,vampireAiController_,logger_,config_),progressionController_(config_,gameEncounterApi_,feedingController_,saintDenisDirector_,logger_){}
Runtime::~Runtime()noexcept{Shutdown();}
bool Runtime::Initialize(HMODULE module){if(initialized_)return true;std::filesystem::path path;if(!ModulePath(module,path)||!gameContext_.Initialize(std::move(path)))return false;bool fileLog=logger_.Initialize(gameContext_.PluginDirectory()/L"Nightwalker.log");logger_.Write(util::LogLevel::Info,std::string("Starting ")+version::kProjectName+" "+version::kString+" (Story Mode only).");if(!fileLog)logger_.Write(util::LogLevel::Warning,"Nightwalker.log unavailable; debugger logging remains active.");const auto iniPath=gameContext_.PluginDirectory()/L"Nightwalker.ini";config_=Config::Load(iniPath,[this](std::string_view m){logger_.Write(util::LogLevel::Warning,m);});systems::LoadSaintDenisSettings(iniPath,config_.encounter,[this](std::string_view m){logger_.Write(util::LogLevel::Warning,m);});narrative::LoadNarrativeSettings(iniPath,config_.narrative,[this](std::string_view m){logger_.Write(util::LogLevel::Warning,m);});logger_.SetMinimumLevel(config_.debug.enabled?util::LogLevel::Debug:util::LogLevel::Info);progressionController_.LoadBeforeSystems(gameContext_.PluginDirectory());debugInput_.Configure(config_.debug);bossRegistry_.ForceClear();shadowstepController_.ReloadPresentationSettings(iniPath);vampireAiController_.ReloadPresentationSettings(iniPath);narrativeController_.LoadScript(gameContext_.PluginDirectory()/L"Nightwalker.dialogue");systems_.clear();systems_.push_back(&progressionController_);systems_.push_back(&debugVampireSpawner_);systems_.push_back(&shadowstepController_);systems_.push_back(&feedingController_);systems_.push_back(&narrativeController_);systems_.push_back(&saintDenisDirector_);systems_.push_back(&vampireAiController_);systems_.push_back(&movementController_);systems_.push_back(&vampireCombatController_);systems_.push_back(&bossHudController_);for(auto*s:systems_)if(s&&!s->Initialize()){logger_.Write(util::LogLevel::Error,std::string("System initialization failed: ")+std::string(s->Name()));for(auto it=systems_.rbegin();it!=systems_.rend();++it)if(*it)(*it)->Shutdown();systems_.clear();bossRegistry_.ForceClear();gameContext_.Reset();logger_.Shutdown();return false;}lastTickMs_=util::MonotonicClock::NowMilliseconds();tickCount_=0;sessionGuard_.Reset();nextBossValidationMs_=lastTickMs_;ResetPerformanceProfile();initialized_=true;logger_.Write(util::LogLevel::Info,"Phase 13 runtime initialized; long-session recovery and compatibility hardening active.");return true;}
void Runtime::Shutdown()noexcept{if(!initialized_)return;CancelSystems();RestoreOwnedState("shutdown");for(auto it=systems_.rbegin();it!=systems_.rend();++it)if(*it)try{(*it)->Shutdown();}catch(...){logger_.Write(util::LogLevel::Error,std::string("System shutdown failed: ")+std::string((*it)->Name()));}systems_.clear();bossRegistry_.ForceClear();debugInput_.Reset();sessionGuard_.Reset();ResetPerformanceProfile();initialized_=false;tickCount_=0;lastTickMs_=0;nextBossValidationMs_=0;gameContext_.Reset();logger_.Write(util::LogLevel::Info,"Nightwalker shutdown complete.");logger_.Shutdown();}
}
