#include "nightwalker/core/Runtime.h"
#include <Windows.h>
#include <algorithm>
#include <array>
#include <filesystem>
#include <string>
#include <utility>
#include "nightwalker/Version.h"
namespace nightwalker::core{namespace{bool ModulePath(HMODULE h,std::filesystem::path&out){if(!h)return false;std::array<wchar_t,32768>b{};DWORD n=::GetModuleFileNameW(h,b.data(),(DWORD)b.size());if(!n||n>=b.size())return false;out=std::filesystem::path(std::wstring_view(b.data(),n));return true;}}
Runtime::~Runtime()noexcept{Shutdown();}
bool Runtime::Initialize(HMODULE h){if(initialized_)return true;std::filesystem::path p;if(!ModulePath(h,p)||!gameContext_.Initialize(std::move(p)))return false;bool logReady=logger_.Initialize(gameContext_.PluginDirectory()/L"Nightwalker.log");logger_.Write(util::LogLevel::Info,std::string("Starting ")+version::kProjectName+" "+version::kString+" (Story Mode only).");if(!logReady)logger_.Write(util::LogLevel::Warning,"Nightwalker.log unavailable; debugger logging remains active.");config_=Config::Load(gameContext_.PluginDirectory()/L"Nightwalker.ini",[this](std::string_view m){logger_.Write(util::LogLevel::Warning,m);});logger_.SetMinimumLevel(config_.debug.enabled?util::LogLevel::Debug:util::LogLevel::Info);debugInput_.Configure(config_.debug);lastTickMs_=util::MonotonicClock::NowMilliseconds();tickCount_=0;unsafeState_=false;initialized_=true;logger_.Write(util::LogLevel::Info,"Phase 1 runtime initialized; no gameplay mechanics are active.");return true;}
void Runtime::Tick(){if(!initialized_)return;++tickCount_;auto now=util::MonotonicClock::NowMilliseconds();double dt=std::clamp((double)(now-lastTickMs_)/1000.0,0.0,0.25);lastTickMs_=now;auto state=gameContext_.QueryRuntimeState();if(state.Unsafe()){if(!unsafeState_){logger_.Write(util::LogLevel::Info,"Game transition detected; cancelling systems and restoring owned state.");CancelSystems();RestoreOwnedState("game transition");}unsafeState_=true;return;}unsafeState_=false;if(!debugDebounce_.IsArmed()||debugDebounce_.HasElapsed(now)){auto a=debugInput_.Poll();if(a.reloadConfig){ReloadConfig();debugDebounce_.Arm(now,250);}else if(a.restoreState){logger_.Write(util::LogLevel::Info,"Debug cleanup requested.");CancelSystems();RestoreOwnedState("debug cleanup");debugDebounce_.Arm(now,250);}}FrameContext f{now,dt};for(auto*s:systems_)if(s)s->Update(f);}
void Runtime::ReloadConfig(){config_=Config::Load(gameContext_.PluginDirectory()/L"Nightwalker.ini",[this](std::string_view m){logger_.Write(util::LogLevel::Warning,m);});logger_.SetMinimumLevel(config_.debug.enabled?util::LogLevel::Debug:util::LogLevel::Info);debugInput_.Configure(config_.debug);logger_.Write(util::LogLevel::Info,"Configuration reloaded.");}
void Runtime::CancelSystems()noexcept{for(auto it=systems_.rbegin();it!=systems_.rend();++it)if(*it)try{(*it)->Cancel();}catch(...){logger_.Write(util::LogLevel::Error,"System cancellation failed.");}}
void Runtime::RestoreOwnedState(std::string_view why)noexcept{auto owned=watchdog_.OwnedCount();auto failed=watchdog_.RestoreAll();if(failed)logger_.Write(util::LogLevel::Error,std::string("Cleanup failures: ")+std::to_string(failed)+" ("+std::string(why)+")");else if(owned)logger_.Write(util::LogLevel::Info,std::string("Restored owned state: ")+std::to_string(owned));}
void Runtime::Shutdown()noexcept{if(!initialized_)return;CancelSystems();RestoreOwnedState("shutdown");for(auto it=systems_.rbegin();it!=systems_.rend();++it)if(*it)try{(*it)->Shutdown();}catch(...){logger_.Write(util::LogLevel::Error,"System shutdown failed.");}systems_.clear();debugInput_.Reset();initialized_=false;tickCount_=0;lastTickMs_=0;unsafeState_=false;gameContext_.Reset();logger_.Write(util::LogLevel::Info,"Nightwalker shutdown complete.");logger_.Shutdown();}
}
